version: '3'
services:
  site:
    build: site
    container_name: apache2
    ports :
     - "3000:80"
    volumes:
     - ./www:/var/www/html/
     - ./apache2config/000-default.conf:/etc/apache2/sites-available/000-default.conf
     - ./apache2config/apache2.conf:/etc/apache2/apache2.conf
    depends_on:
     - database

  database:
    image: mariadb
    container_name: mariadb
    ports :
     - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: docker
#    volumes:
#      - db_data_mvc:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    depends_on:
      - database
    ports:
      - 8000:80
    environment:
      MYSQL_ROOT_PASSWORD: admin
      PMA_HOST: database

volumes:
    db_data_mvc:
      
